sudo: required

language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - git clone -b print-logs git://github.com/joshmoore/omero-test-infra .omero

script:
  - env LOGS=true .omero/docker app
